### ISSUE TITLE
Add metadata to pages

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#76]
## 📄 Context

Currently, we are not displaying customised metadata for pages. For home we display `cartesiscan.io`, for applications page - `cartesiscan.io/applications`. I think we can leverage [next metadata object](https://nextjs.org/docs/app/api-reference/functions/generate-metadata) to display a bit more friendly title and description. This will be beneficial for SEO as the app grows and we introduce more pages to it.

I suggest that we use the following format for titles - `CartesiScan` (for home), `CartesiScan - Applications` (for applications) and `CartesiScan - Applications - [address]`.

For descriptions, I'm open to suggestions about what should the text for each page be. I can discuss this with Dimitar as we did something similar with him for the Explorer app.

## ✔️ Solution

Leverage [next metadata object](https://nextjs.org/docs/app/api-reference/functions/generate-metadata) to display more customised metadata like title and description.

## 📈 Subtasks

- [x] Add title and description for home, applications and application/[address] pages.

## 🎯 Definition of Done

- [x] We have meaningful titles and description for home, applications and application/[address] pages.

**Comment by nevendyulgerov** [comment]
Hey @brunomenezes , @tuler , please let me know if this makes sense to you. If you are ok with this feature, I can tackle it in the next days.

**Comment by brunomenezes** [comment]
Hi @nevendyulgerov, 
That is a good one to include. I will add some suggestions because that application differs from the Staking. Update the issue as you see fit. Reading the docs makes it possible to define a template, making it easier for child pages to define their title. 

My copy suggestion for the `title` template would be: `%s | CartesiScan`
The copy suggestion for the `description` would be: **"CartesiScan is a tool for inspecting and analyzing Cartesi rollups applications. Blockchain explorer for Ethereum Networks."**

| Page | Title | 
| ------------- | ------------- |
| `\` | `Blockchain Explorer \| CartesiScan` | 
| `\applications` | `Applications \| CartesiScan` | 
| `\applications\[address]`| `Application [address] \| CartesiScan`  |
| `\inputs` | `Inputs \| CartesiScan`  |


cc: @tuler, any notes or suggestions?

**Comment by nevendyulgerov** [comment]
Hi @brunomenezes , I'm removing the `triage` status for this task and will proceed with it. If Danilo has any comments I'll address them on the fly.
