### ISSUE TITLE
Configure absolute paths and module path aliases

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#85]
## 📄 Context

Let's configure module path aliases so this:

```
import MyComponent from '../../components/MyComponent';
```

can become this:

```
import MyComponent from '@components/MyComponent';
```

Please use the following [guide](https://nextjs.org/docs/app/building-your-application/configuring/absolute-imports-and-module-aliases) for this.

## 🎯 Definition of Done

- [ ] Correct module path aliases are set

**Comment by brunomenezes** [comment]
Hey @nevendyulgerov, I have a few concerns because, in the past, I discussed that with @tuler, and we decided not to pursue that path. It may fall in the same category as the `index.js,` which is nice but brings problems with time, like `heavy loading`. 

Some questions to balance the pros and cons related to the impact of this:
* Will that require more configurations/dependencies to be added for other toolings to work correctly? e.g. `Vitest`
* How does this aliasing work? Expanding the path on demand or loading everything at once? Does it increase HMR on development? 
* Will the code editors be able to suggest auto-import correctly? If not, is it necessary to add configurations or plugins to work correctly?


#### Final Thoughts
Even though it is nice to see `@/components/whatever` rather than `../../../components/whatever`, the latter tells you exactly where to find what you are importing. Also, the editor/IDE usually does the import for you, removing the hassle. On the other hand, when more configurations and dependencies need to be added for all the different parts to work correctly, including editors/IDE, the cost is too high only for a nicety.

**Comment by tuler** [comment]
I don't see much value as well in aliasing.

**Comment by nevendyulgerov** [comment]
Understood, closing this one as not needed
